// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrendingMovies.proto

package com.moviecatalogservice.proto;

public final class TrendingMoviesOuterClass {
  private TrendingMoviesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetTopTenMoviesReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetTopTenMoviesReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .MovieRating movieRatings = 1;</code>
     */
    java.util.List<com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating> 
        getMovieRatingsList();
    /**
     * <code>repeated .MovieRating movieRatings = 1;</code>
     */
    com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating getMovieRatings(int index);
    /**
     * <code>repeated .MovieRating movieRatings = 1;</code>
     */
    int getMovieRatingsCount();
    /**
     * <code>repeated .MovieRating movieRatings = 1;</code>
     */
    java.util.List<? extends com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRatingOrBuilder> 
        getMovieRatingsOrBuilderList();
    /**
     * <code>repeated .MovieRating movieRatings = 1;</code>
     */
    com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRatingOrBuilder getMovieRatingsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GetTopTenMoviesReply}
   */
  public  static final class GetTopTenMoviesReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetTopTenMoviesReply)
      GetTopTenMoviesReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetTopTenMoviesReply.newBuilder() to construct.
    private GetTopTenMoviesReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetTopTenMoviesReply() {
      movieRatings_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetTopTenMoviesReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetTopTenMoviesReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                movieRatings_ = new java.util.ArrayList<com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating>();
                mutable_bitField0_ |= 0x00000001;
              }
              movieRatings_.add(
                  input.readMessage(com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          movieRatings_ = java.util.Collections.unmodifiableList(movieRatings_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_GetTopTenMoviesReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_GetTopTenMoviesReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply.class, com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply.Builder.class);
    }

    public static final int MOVIERATINGS_FIELD_NUMBER = 1;
    private java.util.List<com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating> movieRatings_;
    /**
     * <code>repeated .MovieRating movieRatings = 1;</code>
     */
    public java.util.List<com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating> getMovieRatingsList() {
      return movieRatings_;
    }
    /**
     * <code>repeated .MovieRating movieRatings = 1;</code>
     */
    public java.util.List<? extends com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRatingOrBuilder> 
        getMovieRatingsOrBuilderList() {
      return movieRatings_;
    }
    /**
     * <code>repeated .MovieRating movieRatings = 1;</code>
     */
    public int getMovieRatingsCount() {
      return movieRatings_.size();
    }
    /**
     * <code>repeated .MovieRating movieRatings = 1;</code>
     */
    public com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating getMovieRatings(int index) {
      return movieRatings_.get(index);
    }
    /**
     * <code>repeated .MovieRating movieRatings = 1;</code>
     */
    public com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRatingOrBuilder getMovieRatingsOrBuilder(
        int index) {
      return movieRatings_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < movieRatings_.size(); i++) {
        output.writeMessage(1, movieRatings_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < movieRatings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, movieRatings_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply)) {
        return super.equals(obj);
      }
      com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply other = (com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply) obj;

      if (!getMovieRatingsList()
          .equals(other.getMovieRatingsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMovieRatingsCount() > 0) {
        hash = (37 * hash) + MOVIERATINGS_FIELD_NUMBER;
        hash = (53 * hash) + getMovieRatingsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetTopTenMoviesReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetTopTenMoviesReply)
        com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_GetTopTenMoviesReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_GetTopTenMoviesReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply.class, com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply.Builder.class);
      }

      // Construct using com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMovieRatingsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (movieRatingsBuilder_ == null) {
          movieRatings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          movieRatingsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_GetTopTenMoviesReply_descriptor;
      }

      @java.lang.Override
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply getDefaultInstanceForType() {
        return com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply.getDefaultInstance();
      }

      @java.lang.Override
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply build() {
        com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply buildPartial() {
        com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply result = new com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply(this);
        int from_bitField0_ = bitField0_;
        if (movieRatingsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            movieRatings_ = java.util.Collections.unmodifiableList(movieRatings_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.movieRatings_ = movieRatings_;
        } else {
          result.movieRatings_ = movieRatingsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply) {
          return mergeFrom((com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply other) {
        if (other == com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply.getDefaultInstance()) return this;
        if (movieRatingsBuilder_ == null) {
          if (!other.movieRatings_.isEmpty()) {
            if (movieRatings_.isEmpty()) {
              movieRatings_ = other.movieRatings_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMovieRatingsIsMutable();
              movieRatings_.addAll(other.movieRatings_);
            }
            onChanged();
          }
        } else {
          if (!other.movieRatings_.isEmpty()) {
            if (movieRatingsBuilder_.isEmpty()) {
              movieRatingsBuilder_.dispose();
              movieRatingsBuilder_ = null;
              movieRatings_ = other.movieRatings_;
              bitField0_ = (bitField0_ & ~0x00000001);
              movieRatingsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMovieRatingsFieldBuilder() : null;
            } else {
              movieRatingsBuilder_.addAllMessages(other.movieRatings_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating> movieRatings_ =
        java.util.Collections.emptyList();
      private void ensureMovieRatingsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          movieRatings_ = new java.util.ArrayList<com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating>(movieRatings_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating, com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.Builder, com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRatingOrBuilder> movieRatingsBuilder_;

      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public java.util.List<com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating> getMovieRatingsList() {
        if (movieRatingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(movieRatings_);
        } else {
          return movieRatingsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public int getMovieRatingsCount() {
        if (movieRatingsBuilder_ == null) {
          return movieRatings_.size();
        } else {
          return movieRatingsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating getMovieRatings(int index) {
        if (movieRatingsBuilder_ == null) {
          return movieRatings_.get(index);
        } else {
          return movieRatingsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public Builder setMovieRatings(
          int index, com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating value) {
        if (movieRatingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieRatingsIsMutable();
          movieRatings_.set(index, value);
          onChanged();
        } else {
          movieRatingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public Builder setMovieRatings(
          int index, com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.Builder builderForValue) {
        if (movieRatingsBuilder_ == null) {
          ensureMovieRatingsIsMutable();
          movieRatings_.set(index, builderForValue.build());
          onChanged();
        } else {
          movieRatingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public Builder addMovieRatings(com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating value) {
        if (movieRatingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieRatingsIsMutable();
          movieRatings_.add(value);
          onChanged();
        } else {
          movieRatingsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public Builder addMovieRatings(
          int index, com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating value) {
        if (movieRatingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieRatingsIsMutable();
          movieRatings_.add(index, value);
          onChanged();
        } else {
          movieRatingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public Builder addMovieRatings(
          com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.Builder builderForValue) {
        if (movieRatingsBuilder_ == null) {
          ensureMovieRatingsIsMutable();
          movieRatings_.add(builderForValue.build());
          onChanged();
        } else {
          movieRatingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public Builder addMovieRatings(
          int index, com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.Builder builderForValue) {
        if (movieRatingsBuilder_ == null) {
          ensureMovieRatingsIsMutable();
          movieRatings_.add(index, builderForValue.build());
          onChanged();
        } else {
          movieRatingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public Builder addAllMovieRatings(
          java.lang.Iterable<? extends com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating> values) {
        if (movieRatingsBuilder_ == null) {
          ensureMovieRatingsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, movieRatings_);
          onChanged();
        } else {
          movieRatingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public Builder clearMovieRatings() {
        if (movieRatingsBuilder_ == null) {
          movieRatings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          movieRatingsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public Builder removeMovieRatings(int index) {
        if (movieRatingsBuilder_ == null) {
          ensureMovieRatingsIsMutable();
          movieRatings_.remove(index);
          onChanged();
        } else {
          movieRatingsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.Builder getMovieRatingsBuilder(
          int index) {
        return getMovieRatingsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRatingOrBuilder getMovieRatingsOrBuilder(
          int index) {
        if (movieRatingsBuilder_ == null) {
          return movieRatings_.get(index);  } else {
          return movieRatingsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public java.util.List<? extends com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRatingOrBuilder> 
           getMovieRatingsOrBuilderList() {
        if (movieRatingsBuilder_ != null) {
          return movieRatingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(movieRatings_);
        }
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.Builder addMovieRatingsBuilder() {
        return getMovieRatingsFieldBuilder().addBuilder(
            com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.getDefaultInstance());
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.Builder addMovieRatingsBuilder(
          int index) {
        return getMovieRatingsFieldBuilder().addBuilder(
            index, com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.getDefaultInstance());
      }
      /**
       * <code>repeated .MovieRating movieRatings = 1;</code>
       */
      public java.util.List<com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.Builder> 
           getMovieRatingsBuilderList() {
        return getMovieRatingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating, com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.Builder, com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRatingOrBuilder> 
          getMovieRatingsFieldBuilder() {
        if (movieRatingsBuilder_ == null) {
          movieRatingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating, com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.Builder, com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRatingOrBuilder>(
                  movieRatings_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          movieRatings_ = null;
        }
        return movieRatingsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetTopTenMoviesReply)
    }

    // @@protoc_insertion_point(class_scope:GetTopTenMoviesReply)
    private static final com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply();
    }

    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetTopTenMoviesReply>
        PARSER = new com.google.protobuf.AbstractParser<GetTopTenMoviesReply>() {
      @java.lang.Override
      public GetTopTenMoviesReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetTopTenMoviesReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetTopTenMoviesReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetTopTenMoviesReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.moviecatalogservice.proto.TrendingMoviesOuterClass.GetTopTenMoviesReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Empty();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty.class, com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty)) {
        return super.equals(obj);
      }
      com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty other = (com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        com.moviecatalogservice.proto.TrendingMoviesOuterClass.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty.class, com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty.Builder.class);
      }

      // Construct using com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty getDefaultInstanceForType() {
        return com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty build() {
        com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty buildPartial() {
        com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty result = new com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty) {
          return mergeFrom((com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty other) {
        if (other == com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }

    // @@protoc_insertion_point(class_scope:Empty)
    private static final com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty();
    }

    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.moviecatalogservice.proto.TrendingMoviesOuterClass.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MovieRatingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MovieRating)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string movieId = 1;</code>
     * @return The movieId.
     */
    java.lang.String getMovieId();
    /**
     * <code>string movieId = 1;</code>
     * @return The bytes for movieId.
     */
    com.google.protobuf.ByteString
        getMovieIdBytes();

    /**
     * <code>float rating = 2;</code>
     * @return The rating.
     */
    float getRating();
  }
  /**
   * Protobuf type {@code MovieRating}
   */
  public  static final class MovieRating extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MovieRating)
      MovieRatingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MovieRating.newBuilder() to construct.
    private MovieRating(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovieRating() {
      movieId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MovieRating();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MovieRating(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              movieId_ = s;
              break;
            }
            case 21: {

              rating_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_MovieRating_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_MovieRating_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.class, com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.Builder.class);
    }

    public static final int MOVIEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object movieId_;
    /**
     * <code>string movieId = 1;</code>
     * @return The movieId.
     */
    public java.lang.String getMovieId() {
      java.lang.Object ref = movieId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        movieId_ = s;
        return s;
      }
    }
    /**
     * <code>string movieId = 1;</code>
     * @return The bytes for movieId.
     */
    public com.google.protobuf.ByteString
        getMovieIdBytes() {
      java.lang.Object ref = movieId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        movieId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RATING_FIELD_NUMBER = 2;
    private float rating_;
    /**
     * <code>float rating = 2;</code>
     * @return The rating.
     */
    public float getRating() {
      return rating_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMovieIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, movieId_);
      }
      if (rating_ != 0F) {
        output.writeFloat(2, rating_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMovieIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, movieId_);
      }
      if (rating_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, rating_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating)) {
        return super.equals(obj);
      }
      com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating other = (com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating) obj;

      if (!getMovieId()
          .equals(other.getMovieId())) return false;
      if (java.lang.Float.floatToIntBits(getRating())
          != java.lang.Float.floatToIntBits(
              other.getRating())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOVIEID_FIELD_NUMBER;
      hash = (53 * hash) + getMovieId().hashCode();
      hash = (37 * hash) + RATING_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getRating());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MovieRating}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MovieRating)
        com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRatingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_MovieRating_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_MovieRating_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.class, com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.Builder.class);
      }

      // Construct using com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        movieId_ = "";

        rating_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.moviecatalogservice.proto.TrendingMoviesOuterClass.internal_static_MovieRating_descriptor;
      }

      @java.lang.Override
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating getDefaultInstanceForType() {
        return com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.getDefaultInstance();
      }

      @java.lang.Override
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating build() {
        com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating buildPartial() {
        com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating result = new com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating(this);
        result.movieId_ = movieId_;
        result.rating_ = rating_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating) {
          return mergeFrom((com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating other) {
        if (other == com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating.getDefaultInstance()) return this;
        if (!other.getMovieId().isEmpty()) {
          movieId_ = other.movieId_;
          onChanged();
        }
        if (other.getRating() != 0F) {
          setRating(other.getRating());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object movieId_ = "";
      /**
       * <code>string movieId = 1;</code>
       * @return The movieId.
       */
      public java.lang.String getMovieId() {
        java.lang.Object ref = movieId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          movieId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string movieId = 1;</code>
       * @return The bytes for movieId.
       */
      public com.google.protobuf.ByteString
          getMovieIdBytes() {
        java.lang.Object ref = movieId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          movieId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string movieId = 1;</code>
       * @param value The movieId to set.
       * @return This builder for chaining.
       */
      public Builder setMovieId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        movieId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string movieId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMovieId() {
        
        movieId_ = getDefaultInstance().getMovieId();
        onChanged();
        return this;
      }
      /**
       * <code>string movieId = 1;</code>
       * @param value The bytes for movieId to set.
       * @return This builder for chaining.
       */
      public Builder setMovieIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        movieId_ = value;
        onChanged();
        return this;
      }

      private float rating_ ;
      /**
       * <code>float rating = 2;</code>
       * @return The rating.
       */
      public float getRating() {
        return rating_;
      }
      /**
       * <code>float rating = 2;</code>
       * @param value The rating to set.
       * @return This builder for chaining.
       */
      public Builder setRating(float value) {
        
        rating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float rating = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRating() {
        
        rating_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MovieRating)
    }

    // @@protoc_insertion_point(class_scope:MovieRating)
    private static final com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating();
    }

    public static com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MovieRating>
        PARSER = new com.google.protobuf.AbstractParser<MovieRating>() {
      @java.lang.Override
      public MovieRating parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MovieRating(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovieRating> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieRating> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.moviecatalogservice.proto.TrendingMoviesOuterClass.MovieRating getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetTopTenMoviesReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetTopTenMoviesReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovieRating_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovieRating_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024TrendingMovies.proto\":\n\024GetTopTenMovie" +
      "sReply\022\"\n\014movieRatings\030\001 \003(\0132\014.MovieRati" +
      "ng\"\007\n\005Empty\".\n\013MovieRating\022\017\n\007movieId\030\001 " +
      "\001(\t\022\016\n\006rating\030\002 \001(\0022D\n\016TrendingMovies\0222\n" +
      "\017GetTopTenMovies\022\006.Empty\032\025.GetTopTenMovi" +
      "esReply\"\000B\037\n\035com.moviecatalogservice.pro" +
      "tob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetTopTenMoviesReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetTopTenMoviesReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetTopTenMoviesReply_descriptor,
        new java.lang.String[] { "MovieRatings", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_MovieRating_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MovieRating_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovieRating_descriptor,
        new java.lang.String[] { "MovieId", "Rating", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
